run('identification_init');
%% Generate table with different fit values

nb = 1:2:9;
nf = 1:2:9;
nk=0; % delay allready removed from the data

show_plot=false;

% prealloc:
fit = zeros(numel(nb),numel(nf));
aic_value = zeros(numel(nb),numel(nf));

for index_nb = 1:numel(nb)
    disp(nb(index_nb));
    for index_nf = 1:numel(nf)
        [~, ~ ,fit(index_nb,index_nf) , aic_value(index_nb,index_nf) , ~] ...
            = fun_OE_model(nb(index_nb), ...
              nf(index_nf) , ...
              preprocessed_prbs_est, ...
              preprocessed_prbs_val, show_plot );
    end
end

rowLabels = {'nb=1', 'nb=3' , 'nb=5' , 'nb=7' , 'nb=9'};
columnLabels = {'nf=1', 'nf=3' , 'nf=5', 'nf=7' , 'nf=9'};

matrix2latex(fit, './tables/fit_OE_table.tex', ...
            'rowLabels', rowLabels, ...
            'columnLabels', columnLabels, ...
            'alignment', 'c', ...
            'format', '%-6.2f');
matrix2latex(aic_value, './tables/AIC_OE_table.tex', ...
            'rowLabels', rowLabels, ...
            'columnLabels', columnLabels, ...
            'alignment', 'c', ...
            'format', '%-6.2f');